server:
  port: 8080
spring:
  application:
    name: "meliChallenge"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  data:
    mongodb:
      uri: "mongodb+srv://admin:admin@meli.vohwshc.mongodb.net/mutantsDB"
management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      probes:
        enabled: true
