name: 'github-actions-meliChallenge'

on:
  release:
    types: [published]
  push:
    branches:
      - master
      - develop

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build and Test with Gradle
        run: ./gradlew build test --refresh-dependencies --no-daemon --continue
      - name: Execute jacocoMergedReport
        run: ./gradlew jacocoMergedReport
      - name: copy the reportTest to codeCoverage
        run: cp build/reports/jacoco/jacocoMergedReport/jacocoMergedReport.xml jacoco.xml || echo "Code coverage failed"
  docker-build:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: CMD
        run: dir/applications
      - name: Build the Docker image
        run: docker build . --file deployment/Dockerfile --tag meli-challenge:$(date +%s)
  release:
    if: github.event_name == 'release' 
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
